name: Setup
runs:
  using: composite
  steps:
    - uses: bullfrogsec/bullfrog@dcde5841b19b7ef693224207a7fdec67fce604db # v0.8.3

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
        cache: yarn

    - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      id: install-cache
      with:
        path: node_modules/
        key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock') }}

    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --ignore-scripts
      shell: bash
